version: '3.3'

services:
  api:
    image: dido/api
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/user-management-system?allowPublicKeyRetrieval=true&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
    networks:
      - db-network

  db:
    container_name: db
    image: mysql:oracle
    ports:
      - "3307:3306"
    environment:
       - MYSQL_HOST=db
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE= user-management-system
    restart: on-failure
    networks:
      - db-network


networks:
  db-network:
    driver: bridge